"""Types for the TeslaPy 2.9.2 API used by TeslaBot.

SDK response payloads are dynamic dictionaries; session and vehicle operations
have explicit signatures so subclasses and callers remain type checked.
"""

from typing import Any, Callable
import requests

class Tesla(requests.Session):
    timeout: float
    token: dict[str, Any]
    authorized: bool
    code_verifier: bytes | str | None
    def __init__(
        self,
        email: str,
        *,
        timeout: float = ...,
        cache_file: str = ...,
        cache_loader: Callable[[], dict[str, Any]] | None = ...,
        cache_dumper: Callable[[dict[str, Any]], None] | None = ...,
        authenticator: Callable[[str], str] | None = ...,
        **kwargs: Any,
    ) -> None: ...
    def authorization_url(self, url: str = ..., **kwargs: Any) -> str: ...
    def fetch_token(self, token_url: str = ..., **kwargs: Any) -> dict[str, Any]: ...
    def refresh_token(self, token_url: str = ..., **kwargs: Any) -> dict[str, Any]: ...
    def logout(self, sign_out: bool = ...) -> None: ...
    def vehicle_list(self) -> list[Vehicle]: ...
    def api(self, name: str, path_vars: dict[str, Any] | None = ..., **kwargs: Any) -> Any: ...

class VehicleError(Exception): ...

class JsonDict(dict[str, Any]): ...

class Vehicle(JsonDict):
    def __init__(self, vehicle: dict[str, Any], tesla: Tesla) -> None: ...
    def api(self, name: str, **kwargs: Any) -> Any: ...
    def sync_wake_up(self, timeout: float = ..., interval: float = ..., backoff: float = ...) -> None: ...
    def get_vehicle_data(self, endpoints: str = ...) -> Vehicle: ...
    def command(self, name: str, **kwargs: Any) -> Any: ...
